version: "2.2"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    networks:
      - fullstack
    env_file:
      - .env
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - fullstack
volumes:
  db:
networks:
 fullstack:
    driver: bridge