version: "2.2"
services:
  server:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: docker/Dockerfile.dev
    ports:
      - 5000:5000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app